#CLASSCODE CALCULADORAhttps://replit.com/join/pgxbqssvqs-andreasofiasof4
print("SUMA")
SUMA=int(input("Ingrese el primer numero de la suma"))
SUMA2=int(input("Ingrese el segundo numero de la suma"))
print("La suma de estos numeros es:",SUMA+SUMA2)
print("RESTA")
RESTA=int(input("Ingrese el primer numero de la resta"))
RESTA2=int(input("Ingrese el segundo numero de la resta"))
print("La resta de estos numeros es:",RESTA-RESTA2)
print("MULTIPLICACIÓN")
MULT=int(input("Ingrese el primer numero de la multiplicación"))
MULT2=int(input("Ingrese el segundo numero de la multiplicación"))
print("La multiplicación de estos numeros es:",MULT*MULT2)
print("DIVISIÓN")
DIV=int(input("Ingrese el primer numero de la división"))
DIV2=int(input("Ingrese el segundo numero de la división"))
print("La divisón de estos dos numeros es:",DIV/DIV2)
