on=input('What is your name?😎\n')
input()
sex=input("Are you boy or girl?😏\n")
input()
print("You just woke up from your bed at 6:00 am and you need to get early to your job so you decide to go and make some breakfast to yourself 😴")
input()
breakfast=input("What do you want to eat?🧐\n")
input()
print("Great choice, the",breakfast,"was/were delicious, now you need to brush your teeths 😬")
input()
print("While you were washing your teeths you accidentally felt into the mirror 😥")
input()
print("Your head hurts, what happened!? you just woke up again from your bed, but its not exactly your room, I mean, it was your room when you were a kid in the 80 🤭")
input()
print("Oh no!! what happened to me? (you look at your hand) what happened to my body? (you run to the mirror and see your reflection) how did this happened to me, I went back to the past this can't be happening!!! why is this happening to me??? I can't understand it 😰")
input()
print("What can i do???🤔")
input()
print("I have an idea! I'm going to see if my father is in the house (you open the door of your room and go down the stairs of the house to the first floor,you find your father in the kitchen) (you get a little nervous) hello dad, do you remember my age? (your father looks at you a little doubtful)👀🤔")
input()

while True:
  a=int(input("(Guess your age),how old do you think you are?😇\n"))
  if a<=10:
    input()
    print("You are older🤌👆")
    input()
    continue
  if a>11:
    input()
    print("You are younger🤏👇")
    input()
    continue
  if a==11:
    input()
    print("You got it!!!👌")
    break
input()
if sex==("boy"):
 print("Your father tells you doubtful, son you are",a," years old, are you sure you feel good son?🥺😵‍💫")
if sex==("girl"):
 print("Your father tells you doubtful, daughter you are",a," years old, are you sure you feel good daughter?🥺😵‍💫")
input()
v=input("Write your answer 🤓,-Yes, I feel good dad- or -Yes, it was just a joke-:\n")
input()
if v==("Yes, I feel good dad"):
  print("Okay, but don't scare me like that, I was worried.")
if v==("Yes, it was just a joke"):
  print("Don't tease me like that, I was really worried about you 🥺")
input()
print("Well dad,changing the subject, what I really came to ask you is todays date, I think I am a little lost, can you help me?😳")
input()
print("Of course, today is August 29 of 1983, have you forgotten that tomorrow is your first day in middle school? , I remind you that since we just moved from California I hope you can make new friends, although you are a little smaller in age than the other kids I hope you do not have a problem ✨☀️😊")
input()
print("Thanks dad 🥺👍")
input()
print("(You go back to your room and lay down on the bed), I didn't remember that I had moved before I started middle school, but well I can't do anything but wait for tomorrow, (you fell asleep)😴✌️")
input()
if sex==("girl"):
 print("Wake up daughter💫")
if sex==("boy"):
 print("Wake up son🌟")
input()
print("You open your eyes and see your dad waking you up to go to school, this means, THIS WAS NOT A DREAM you are in the 80s 😴")
input()
print("I have no other option, (you get out of bed, you go to take a bath, you change into your new uniform and go down to eat breakfast 😄😏)")
input()
print("You leave the house heading to the school bus 😎😎😎")
input()
s=input("Outside the bus you found a boy you knew in the past, do you want to say hello?(yes or no)🤔:\n")
input()
if s==("yes"):
  print("Hello, I'm new here I'm going to start middle school, nice to meet you 🤠")
  input()
  print("Nice to meet you my name is Evan,I hope we get along, I think we are in the same grade (Evan walk and enter to the bus, you follow him and sit down)😶")
input()
r=input("Suddenly someone hits you from the side on the bus, you realized that it is one of the children that bothered you, decide:(defend now or wait a while to get revenge)😡😇🤯:\n")
input()
if r==("defend now"):
  print("You hit him back and sit back as if nothing had happened 😇")
  input()
  print("The one you hit is confused and no one on the bus notices so the kid stands up and goes to sit down looking doubtful as to what happened 😵‍💫")
  input()
if r==("wait a while to get revenge"):
  print("Sit back and let it go (you're sitting there thinking that someday you'll have a better oportunity to get revenge)🤕😱")
  input()
print("The bus arrives to school and you enter to your classroom, you see some friends in the front 🤗")
input()
sit=input("Where do you want to sit? in front or at the back?🧐\n")
input()
if sit==("front"):
  input()
  print("You take your things to sit in the front and say hello to the people around, they give you space and start talking to you 🥱")
  input()
  print("A girl comes to you to say hi, but you know her , how could you forget her face? she was the girl you were in love with, her name was Allison 😊")
  input()
  print("Hi! my name is allison, whats your name?👀")
  input()
  print("My name is",on,"😶")
  input()
  print("Cool, can I sit with you",on,"?")
  input()
  print("As the teacher arrives you stop talking and she explains the activity ")
  print("You don't listen to the instructions and now the teacher ask you to give an answer👺 ")
  input()
  print("Try to guess the answer")
  print("The answer can be these 5 numbers: 10, 20, 30, 40, 50")
  variable=int(input("Write a number:\n"))

  if variable==10:
   print("The number is 10 and you pass, you feel great and all the classroom start clapping to you, you are like a hero, BUT PUM, you wake up and everything was just a dream, the teacher gets mad and send you to the principal office for being 😩😩😩😩distracted in class.")
  elif variable==20:
   print("The number is 20 and you pass, your friend feels happy because you got it right, but the teacher start thinking that your friend passed you the answer and send you to the principal office🧚🏿‍♂️.")
  elif variable==30:
   print("The number is 30 and you pass, But the teacher was so mad that you got it wright that she sends you to the principal office for being distracted at class.👻👻👻💀🤖🎃👻👾👾")

  else:
   print("Ooh noo! you got it wrong now you will ned to go to the principal office.")
  
  input()
  print("Now you are at the principal office so you feel a little bit scared")
  print("But the principal seems very nice ")
  input()
  print("I know you are",on,"and I know you are not from these year at all, please come with me I need to show you something")
  print("You get out of school and get into the principals car, then the radio started playing a song from Joy Division👾 ")
  input()
  print("Then he gets to a place that is empty and in the middle of nowhere, he stops the car and says, Im a Robot sended from the future to save you ")
  input()
  print("You believe it because after everything that happened to you, this seems real, even because this reminds you to the movie of the Terminator, but you wont say that because that movie hasn't been published yet👦🏿👍🏿.")
  input()
  print("So, why are you protecting me?, you ask.")
  input()
  print("From that gir you met,Allison, she wants to kill you.")
  input()
  print("What!? that's imposible, she was my friend even in my other life when I really was at the age of 11.😕☹️😞🥺")
  input()
  print("So If thats true show me some proofs and then I can believe that")
  input()
  print("Ok if you want some proofs I can show them to you...... The bot show her/him the proof")
  input()
  print("You are in shock because you couldnt believe that but you trust him anyways🧐")
  input()
  print("You invite him to talk more about the case of allison")
  input()
  print("Then the robot or the principal takes you to his car again to show you something")
  input()
  print("You arrive and you watch the house that you had in the past, or in te future, you dont really know anymore🤩")
  input()
  print("You watch allison going out of your house with a knife and you start thinking that the robot was right because then you see your dead body in your room🥺😰")
  input()
  print("Then you start screaming and you pass out ")
  input()
  print("You wake up in a house you don't recognize😏😏")
  input()
  print("You see there is the robot for the future and you remember it all")
  input()
  print("How can we kill her? I dont want that to happen in the future🙃🙃")
  input()
  print("Its easy, lets kill her while she sleeps")
  input()
  print("It doesnt sound so bad")
  input()
  print("So you go to school as if it was a normal day ")
  input()
  print("You try to avoid allison but she comes to you with a knife😅")
  input()
  print("You start running as fast as you can")
  input()
  print("But she arrives, now you need to make a desition")
  input()
  walk=input("Do you want to face her or run?\n")
  if walk==("face her"):
   print("You walk to her and you ask, why do you want to kill me? ")
   input()
   print("because you tried to kill me first, and I wont let you")
   input()
   print("NO! I never tried to kill you ")
   input()
   print(" I dont care what you say, I been waiting so many years and is my time to get revenge😈")
   input()
   print("I wont let you!")
   input()
   print("You start fighting but you got hurt and she is about to kill you🤬")
   input()
   print("You lost all your hopes")
   input()
   print("But then...")
   input()
   print("There is someone there... its a familiar face. ITS THE PRINCIPAL ROBOT!!")
   input()
   print("He is ready to atack, and Allison scapes fast before the robot killed her⚡️")
   input()
   print("What a shame")
   input()
   print("but at least we scape")
   input()
   print("Lets go to get some sleep, come to my house")
   print("ok!")
   input()
   print("as you arrive to the robot house, you see Allison is there, ready to kill you")
   input()
   print(" Come here! the Robot yells")
   input()
   print("you hide and ask, What can we do?")
   input()
   print("Listen kid, I have a secret weapon in my code, it can cause a bomb, like that we can kill her finally!")
   input()
   print(" YES! whats the code !??")
   input()
   print("weell thats the pronlem")
   input()
   print("what do you mean? with that?")
   input()
   print("I dont know the code, ")
   input()
   print("well the you from the past made the code, so it must be your favorite number from two digits ")
   input()
   print("I love th number 4, I think with that we can start, and then?")
  while True:
   b=int(input("(Guess you),Try to guess the code(two numbers):\n"))
   if b<=40:
    input()
    print("It is bigger")
    input()
    continue
   if b>50:
    input()
    print("It is smaller")
    input()
    continue
   if b==46:
    input()
    print("Yes! Now lets activate the bomb!")
    break
  input()


  if walk==("run"):
   print("You run as fast as you can and then you scape hopefully the principal robot is there and he asks what happened?💨☃️")
   input()
   print("I saw Allison, with a knife")
   input()
   print("she was trying to kill me")
   input()
   print("we must hurry up and kill her before she wins the battle🌚")
   input()
   print("I dont know, Im tired, I want to go home💀😨")
   input()
   print("I know but, I shure if we kill her you will come back to your home safe.")
   input()
   print("ok!")
   input()
   print("you go to your house to sleep")
   input()
   print("oooh nooo! it seems like allison won")
   input()
   print("you died")
   input()
   print("...")
   input()
   print("بندعغثيطرمنبتضصثسا باي اعفقث ىاتذذط سيباتتت ددذذز طلثصن صصثثي لياب٨٧٦٥ ١ ٢ ٣")


if sit==("back"):
  
 print("You take your things and sit at the back of the classroom, everyone is watching you with a strange face 🤨📸.")
 input()
 print("Thinking that it is strange that they do not talk to you, you finally decide that you must face what you could not in the past (because of your shyness you could not make friends) you decide to approach your partner in front to talk to him 🥲👌")
 input()
 print("There is a boy who caught your attention in an instant you couldn't take your eyes off him, as you got closer you  realized that he is the boy you liked in the past and you couldn't approach him because you were so shy 😔😍 ")
 input()
 print("You think about talking to him but you are shy so")
 qu=input("Do you want to aproach him?(yes or no):\n")
 input()
 if qu==("yes"):
  print("You've approached him, (this is going to be your first meeting) hello, my name is",on,"nice to meet you, I'm new to this school, I hope we get along, what's your name?😄☺️")
  input()
  print("(He answers you),my name is Rain, I've been in this school for a long time, if you need something just say so(you sit down again)🥳")
  input()
 if qu==("no"):
  print("You get nervous and try to sit back down and trip over the backpack you left on the floor next to your banch, and fall on top of the guy you liked in the past 😥😭")
  input()
  print("I am very sorry, I am new here and Im getting used to it (you get up, extend your hand),I am",on,"and you???(answer) I am Rain, I have been here a long time, if you need anything, just say it, (he gives you the hand and go to your place to sit down)😍🤭")
  input()
 print("When you sit down, your remember that you have an old computer, try to guess the password 🤪")
 input()
 c=25
 fo=int(input("Guess te password:(two numbers)🥳😒:\n"))
 while fo!=c:
  print("Guess another time")
  fo=int(input("Guess te password:(two numbers):\n"))
 else:
  print("You got it!")
  input()
  print("Now you want to change your password for somthing more easier 😜")
  input()

  import random

  base="abcdefghijknmñopqrstuvwxyz1234567890@#$*&"


  passw=""
 e=int(input("Write the numbers of characters in the password😏:\n"))
 for i in range(e):
  passw=passw+random.choice(base)
 
 print("The new password is", passw)
 input()
 print("Dont forget it!😵‍💫")
 input()
 print("The day passed quickly, and it was time to go home, when you arrived at your house and entered your room you stumbled on something on the floor, you pick it up and you realize it is a book and when you open it, you found your diary, but there is something strange in that diary, there are several important data from the future that still dont happen, but almost the instant you start reading, everything in the book disappears, and something new appears: when you need it the words will appear although a little confused you realize that at last you found a clue why you were returned to the past, at that moment you decided that the diary will be very important to your life in the future and that you would take it with you wherever you go 😵‍💫🤯😬👾 ")
 input()
 t=input("You go to sleep and when you wake up you decide to open the book, write (r) to read what it says🧐:\n")
 input()
 if t==("r"):
  print("Interesting fact: Rain is a shy person inside, if you want to get close to him be kind and get closer little by little 🤫")
 input()
 print("At that time you thought that journal had a purpose, its purpose was not yet clear, and you thought,(I’m going to find out why this journal wants to influence my life, what is its purpose?)😱 ")
 input()
 ra=input("You go to school to test the effectiveness of the diary, you see that Rain is thrown to the ground for carrying too many books, you kindly come over to help him and tell him (choose the letter of the answer) -(w)wait I'm going to help you, you're the one I met yesterday right?, I hope we can be friends- or -(b)you help him pick up the books and tell him, it's good to see you again:\n")
 input()
 if ra==("w"):
  print("Rain blushes and says he hopes they can be friends too and runs away 🤩  ")
  input()
 if ra==("b"):
  print("Rain thanks blushing and runs away 😙😜")
  input()
 print("You think, (Apparently this diary is right, but in what course do you want to take my life, will it be good or bad?) 🤔🤔🤔")
 input()
 print("YOU WANT TO TAKE FRESH AIR,You tell your father that you want be in charge of buying the things that you need in the house, he gives you a list telling you that you can add whatever you want, but only one thing, what will you buy?🤔🤫... ")
 input()
 super=["shampoo","meat","apples","tomatoes","shrimp"]
 print("The number of articles in the list is:",(len(super)))
 input()
 print(super)
 input()
 arti=input("Add an item to your list, write it:\n")
 super.append(arti)
 input()
 print("Your new list is:",super)
 input()
 fi=input("After buying the supermarket on the way back to your house you find a fight in an alley when you get closer you realize that who they are hitting is Rain in an attempt to take his money, you want to help him but you don't know what to do since you don't want him to see your face, you still have the knowledge of your adult life, so it occurs to you to look at your diary and say (grab the black cloak that is behind you on the floor, enter the scene to save him), following the advice of the diary you enter the fight as you plan to knock out the assailants,choose (-with a kick- or -with a punch-):\n")
 input()
 print("[O\\\\\[========================-")
 input()
 if fi==("with a kick"):
  print("You put on the black cloak, you run towards the wall to push yourself and give a spinning kick to one of the assailants, while the other assailant tries to hit you from behind, you crouch down avoiding his blow to give him a punch in the abdomen immobilizing both assailants, then someone lightly pulls your cloak from behind but that was Rain who timidly said thank you 😈🤕👻")
  input()
  print("Realizing that Rain had a small wound on her arm you tore a piece of cloth from the black cloak to cover her wound, then realizing that I could recognize you, you ran away immediately, and in your flight you left grabbing the supermarket bag that you left on the ground to be able to fight, when you got home you hid the cape and handed over the supermarket bag and after you were so tired you fell asleep 😴😴")
 input()
 if fi==("with a punch"):
  print("You put on the black cape and sneak up and punch one of the assailants but that's not enough to knock him out and he fights back by throwing a punch back but you dodge it and hit him in the abdomen knocking him out and then someone attacks you from behind but you react quickly with a kick and you knock him out 😵‍💫🤕")
  input()
  print("Someone lightly pulls your cloak from behind but that was Rain who timidly said thank you, realizing that Rain had a small wound on his arm you tore a piece of cloth from the black cloak to cover his wound, then realizing that I could recognize you, you ran away immediately, and in your flight you left grabbing the supermarket bag that you left on the ground to be able to fight, when you got home you hid the cape and handed over the supermarket bag and after you were so tired you fell asleep 🥸😴")
 input()
 print("Memories from the past:")
 input()
 print(on,"after being bullied during his time at school when he grew up he decided that it would never happen again, so he learned martial arts, almost everything, and became an expert in each one of them, since he made that promise to himself he hasn't He let them abuse him or someone else again, well although that was not his job, he is even better at his job than in martial arts😱😱🤔🦈")
 input()
 print("You wake up and go to school, you are very worried about what happened yesterday and you want to see how Rain is doing, when you get to school you sit down and you notice Rain a little weird so you either invite him to eat🍥🧃🍇")
 input()
 print("Rain acept,but there's something Rain wants to tell you about and says, (so far you're the only person I consider my friend and I want to tell you something, yesterday walking home I was assaulted, but someone saved me and I think I want to find him and thank him, -he blushed a bit-) you respond, (well that you were saved, but from now on I decided to walk with you the way home for precaution, Rain says thank you and you answer, I wait for you at the entrance at the time of departure, and you leave 😐😶😶")
 input()
 print("While returning to the house by his side you discovered several new things about him, for example where he lives, the things he likes and you even began to talk more openly, and after 2 months you were already best friends 😬🎉🎊 ")
 input()
 print("But there was a problem, and that was that Rain still hadn't lost interest in the hooded man and kept looking for him whenever he could since he was becoming more and more interested in him, but his interest couldn't be helped since the hooded man was starting to be known by the people at the neighborhood 🥋🥷🏻")
 input()
 print("After happened with Rain you had decided that you were not going to do it anymore, but a few days after that you saw a child being hit by an adult near your house and you couldn't resist, several more incidents attracted your attention and you couldn't help but repeat it , until you finally realized that you couldn't stop, it was your nature not to let someone suffer as you suffered 🧒🏿👀🤕🤫")
 input()
 er=int(input("You decided that you will protect him but you can't do that by revealing your identity, and it's very dificult to hide it, and worst of all, you go with him in his searches for the hooded man knowing that he is not going to find anything (you're feeling bad about it), so you've decided to ask for advice in the diary, when you opened it a few words appeared saying, you have 2 options 1- leave the hood or 2- make yourself even closer to Rain,write the number of the option you pick 🤩🤨🤔:\n"))
 input()
 if er==1:
  print("I need to leave the hood, I need to spend my days away of it, I can't continue living like this😥")
  input()
  print("You past your days with Rain, but he can't forget the hooded man,I spend my days searching the hooded man with Rain knowing that he won't appear again, but someting dangerous happened?..")
  input()
  print("While you were walking home with Rain,some people come in a car and take Rain away with them, and withouth thining another time you began to follow the car jumping from one building to another to reach it and finally arriving at an abandoned warehouse where the kidnappers parked, you silently followed them to where they took Rain😼")
  input()
  print("You had to disguise yourself, you could never forget the cloak, because you took it with you, then hiding, you took them by surprise surprising and defeating the thieves, and you took Rain to a place near the warehouse, then you disappeared from his sight thinking a at the same time if I want to protect him I need to be the hooded man🥷🏻")
  input()
  
 if er==2:
  print("You spend all your free time with Rain, but something hapened,while you were walking home with Rain,some people come in a car and take Rain away with them, and withouth thining another time you began to follow the car jumping from one building to another to reach it and finally arriving at an abandoned warehouse where the kidnappers parked, you silently followed them to where they took Rain🤫🥷🏻")
  input()
  print("You had to disguise yourself a the hooded man, then hiding, you took them by surprise surprising and defeating the thieves, and you took Rain to a place near the warehouse, then you disappeared from his sight🥷🏻")
  input()

 print("Something was wrong, why do these incidents happen so often to Rain? You didn't have time, you took off your cape and ran to him as if you were looking for him, he told you what happened then you you take him home and once he gets in safely you go home and try to find answers, why is RAIN ALWAYS IN DANGER???😡😤")
 input()
 print("I need to investigate")
 input()
 print("This is strange, you couldn't find anything about Rain, but something wasn't right, you knock on the door of her house and a lady opens it and says you're the one who came to see the house, where are your parents, like to see the house, not here does Rain live?")
 input()
 print("I think you are confused,we are renting this house that is not possible 🤭🤖")
 input()
 yun=input("Chose 1 or 2:\n")
 input()
 if yun==("1"):
  print("Sir, I think you are confused, what address are you looking for? You very confused go away 😥😰")
  input()

 if yun==("2"):
  print("You very confused run away 😶")
  input()

 print("After that you didn't see Rain in school, shortly after you found out that Raiden had moved, once he got back to school, he told you that he had moved house because someone had broken into his house a few days ago and killed his dog leaving a message -the next one it's going to be you and not just a dog- 🐶")
 input()
 print("You think, I need to found who is the person who is putting Rain's life at risk 🥶🥶 ")
 input()
 print("But why?, this had not happened in my reality 😖")
 input()
 print("Is it my fault? 🤬")

 input()
 print("I have no option, I need to found the culprit 🥋😕") 
 input()
 print("You follow Rain to every place you can, your relationship is even closer than before, but you can't lose concentration, you have to protect him!!! 😤")
 input()
 bna=input("While you were walking with him back to his house you notice something, someone is following you, choose -chase the person after leaving rain at his house (6)- or -leave Rain with some excuse and chase the culprit (7 )- WRITE THE NUMBER🫥 :\n")
 if bna==("6"):
  print("You leave Rain at his house and then try to follow the person who was following Rain, but after following him for three streets you lost him in the dead of night. Then you go to your house ...") 
 if bna==("7"):
  print("You tell Rain that you had to do something and you leave, you chase the culprit but he escapes, then you go home...")
 input()
 print("After you leave, you went to your house but your father is waiting you in the frontdoor of the house and shows you a card from school saying you are too distracted and low in grades so he said that after school you have to stay in home and nothing of running away from home.... You agree 🤥 ")
 input()
 print("You take a bath and eat something from the kitchen,then you go to sleep but you could only sleep 5 hours because you were worried about Rain")
 input()
 print("Then you tell your father that you promise to have more than 9 in all your subjects and that if you don't fulfill it you will pay attention but that for you it is very important to spend time with your best friend   🥲😢🥺")
 input()
 print("He acept becauce he is very happy since you were finally able to make friends, but he only leaves you with one condition and that is that you introduce him to your friend (Rain) and he tells you to invite him to the house 😄😜") 
 input()
 print("You get happy and the next day you ask Rain if he can go to your house, he says yes but that he would have to return to his house before 8 at night because of what is happening and you accept 🥳🥳")
 input()
 print("After school you and Rain walk to your house")
 input()
 print("They knock on the door and your father opens it...😱😨")
 input()
 print("Your father opens the door and he happily say hi to Rain and both go inside the house to show Rain your house👻")
 input()
 print("Rain likes your house and you go eat something, you guys are hungry 🤤")
 input()
 print("Rain call her mother and he asks her permission to stay the night since your father was very insistent that he stay the night 😓🤥")
 input()
 print("At night the intruder enters the room, but luckily you woke up in time to save Rain 🔪")
 input()
 print("From the impact Rain wakes up but, there is something wrong, he has seen you protecting him...")
 input()
 print("In that moment you remember something, when you were little Rain had had a mysterious death, you cried his death for weeks, a dark part of your life, you had forgotten that's why you became a detective, only with the passage of time you forgot, you wanted to find his killer 🔪🔪😡")
 input()
 print("IN THIS LIFE you will not let it happen, when you were losing your strength you remembered it, you took the knife from the murderer, he said at that moment, tell your uncle to pay his money or you would die and the next ones will be his family and he go out through the window 🤪🤬")
 input()
 print("Rain realizes that you are the man in the cape, the one who always protects him, shortly after the murderer left, he hugs you and both blush 🥰😳") 
 input()
 print("Rain said thank you")
 input()
 print("You have no choice but to tell him what happens but before that you should check your diary, when you open it the diary tells you:")
 input()
 print("Tell the truth without mentioning the trip to the past or the future 😶‍🌫️")
 input()
 print("You tell him that you decided that you wanted to put on the cape when you saw how they abused people without being able to defend themselves, but seeing that he was in danger, you decided to protect him in secret 😑😮")
 input()
 print("Rain tells you that his uncle owes money and has run away and they can't find him, apparently he likes to gamble and was scammed, and now they're looking for him to pay 🤑")
 input()
 print("You notice a drop of blood on the floor, and you realize that the assassin is injured, you tell Rain to wait and you go out the window 🤫😑")
 input()
 print("You start folowing the assasin 🥸")
 input()
 print("He does not realize it and enters an abandoned casino, you think there is nothing and you enter, you realize the people inside and you hide, you hear them talking and you realize that this is a money laundering center, you sneak into the administration office and look in the records 🤩🤩🤩")
 input()
 print("You find Rain's uncle and find that he and many other gambling addicts were scammed, you hear a noise and you hide, the murderer and someone else enters the room 🤫😓")
 input()
 print("You hide under the table, you hear them say that the business is prospering, and the other person laughs and says yes with all the people scammed, the killer mentions that he failed the last mission and will not do it again, and the other one that you realize is the boss says,you better not fail again 🥶😱")
 input()
 print("You then steal the records by going out a window in the room after the killer and the boss leave the room and come up with a plan 😠")
 input()
 print("You meet with Rain and tell him the plan, at night Rain is going to leave an envelope with the documents in the police, and at the same time you are going to start a little fire in the office of the abandoned casino to delay the discovery of stolen documents 😬")
 input()
 print("Rain's part is carried out perfectly, but when you enter you realize that there is still people inside, so you have the idea of starting a small fire in a visible place, and it worked, could evacuate in time, but something goes wrong and it is difficult for you to evacuate 🆘")
 input()
 print("But there is still someone inside, the boss in his office,you have no choice but to go to the office, and when you find him passed out you have no choice but to take him and jump out of the window, you call the doctors and make an anonymous call to the police, almost resulting in an immediate arrest 🤩🤟") 
 input()
 print("The killer hasn't been caught yet, so you stayed with Rain most of the time to make sure nothing bad happened 😜")
 input()
 print("Their relationship is getting better and better, when you go to Rain's house to sleep you hear strange noises, you hide under the bed and shortly after you see the murderer enter the room, take out a knife and try to bury it in Rain😡😰")
 input()
 ty=int(input("You quickly come out of hiding and manage to remove the knife, but in a bad move it buries itself in your leg, but you try to contain the pain so as not to wake Rain, choose 1 or 2: 🥶😱😨\n"))
 input()
 if ty==1:
  print("He pulls the knife out of your leg and tries to stab you back, but in an accident he sticks it in his stomach, you call an ambulance and the police to have him arrested and his injuries treated as soon as possible, Rain wakes up to see what what is happening and hugs you, so as not to worry Rain you hide your wound 😩")
  input()
  print("When everything is over Rain realizes that you are bleeding, but you tell him that you are fine and a few seconds later you pass out, while you are unconscious you find a shadow that tells you, you have fulfilled your mission, your reward is in the future, then you wake up and you are back in your future but now many things have changed 😇😊")
  input()
  print("Now you are not alone, now Rain has married you, and although you are still a detective you are happy with your work and now you enjoy your days with Rain 🥰🤓")
  input()
  print("END []++++||=======> ")
 if ty==2:
  print("Then, in the distraction of the murderer, you take the knife out of your leg and hit him on the head with the handle, leaving him unconscious, since at the moment you cannot stand up, you call Rain and he is worried and hugs you and you tell him to call the police, fortunately they arrived before the killer regained consciousness, being arrested, there was a lot of blood, by the time Rain noticed it, you had already passed out 😩")
  input()
  print("While you are unconscious you find a shadow that tells you, you have fulfilled your mission, your reward is in the future, then you wake up and you are back in your future but now many things have changed 😇😊")
  input()
  print("Now you are not alone, now Rain has married you, and although you are still a detective you are happy with your work and now you enjoy your days with Rain 🥰🤓")
  input()
  print("END []++++||=======> ")