saludo="Hello"
print(saludo)
print("Write your name:")
nombre=input()
print("your name is:",nombre)
print("Write your grade:")
grado=input()
print("your grade is:",grado)
print("Write your group:")
group=input()
print("Your group is:",group)
print("Write your favorite food:")
food=input()
print("Your favorite food is:",food)
print("Write something interesting about you:")
you=input()
print("Something interesting about you is:",you)
print("END")